version: "3.8"

services:
  postgres:
    image: postgres:16.2
    container_name: postgres
    ports:
      - "55432:5432"
    environment:
      POSTGRES_USER: shoply_backend_user
      POSTGRES_PASSWORD: 1qaz2wsx
      POSTGRES_DB: shoply
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: